// try catch

const numero1 = 20;
const numero3 = 30;

console.log(numero1);

// Errores sin parar la ejecución del código
try {
    console.log(numero2);
} catch (error) {
    console.log(error);
}

console.log(numero3);